### ISSUE TITLE
Time Warp years/days/hours is not precise

### ISSUE THREAD

**Issue by ntwest** [ntwest/TimeControl#1]
Seeing weird behavior in Kopernicus when I warp for "1 day".

**Comment by angrybold** [comment]
Weird behavior as in the warp cuts out before the time is up.
Might be related to a new version of kOS.
I'll see what i can find.

EDIT: probably not related to kOS. Removing Time Control will solve the issue. It seems the sudden stop happens, when usually the time warp would start slowing down.

**Comment by ntwest** [comment]
How does removing solve the issue?? The auto-warp for X time feature is part of Time Control....?

It appears the built in auto-warp function is doing some kind of math to cut off early. I'll have to implement an auto-warp manually.

**Comment by ntwest** [comment]
Fixed with new manual warping code.
