### ISSUE TITLE
Store or auto-calculate context-dependent limits for physics warp.

### ISSUE THREAD

**Issue by Bristicus** [ntwest/TimeControl#25]
(2nd EDIT: Have now fixed problem with the title.)

Hi! Dunno if any of this is covered by other requests (I didn't understand all the ones I read!), so I'll describe it here and see what folks say.

What I'd like to be able to do is use much higher physics warp rates than x4 *when it is safe to do so*. To do this safely, I either need to be able to set custom limits for myself, or have them set automatically, for how far the physics warp can be increased in different contexts.  

Here are some of the limits I think might be useful: 

Limits based on ship status:
 - Either limit the amount of thrust that engines can use when using high physics warp rates, OR automatically reduce physics warp rate if thrust (or acceleration) get too high. (Basically, one should be limited in proportion to the reciprocal of the othe.r)

Limits based on atmosphere, e.g.:
 - When in vacuum, allow up to x8 or x10, or even more (useful for when using ion drives!). 
 - When low in Kerbin's atmosphere, limit phys warp to x3, but when above 20km allow up to x4. 
 - When on Duna or in other thin atmospheres, allow x4; 
Possibly this could actually be based on atmospheric density or pressure, rather than on each planet/moon and altitude, so that it automatically scales.

Limits based on other environmental factors
 - Limit physics warp rate based on local gravity strength.
 - When closer than 1km to any surface, limit phys warp to x2.
 - When closer than 100m to any surface/object, limit phys warp to x1.

Together, these limits should enable players to use physics warp much more in the game, while being protected from catastrophes that come from the physics model losing accuracy in the most challenging physical situations.

Thanks for the mod, and keep up the good work! =:o}

**Comment by ntwest** [comment]
I have found that physics goes really wonky once you get past x 6. Essentially what it does is *skip* physics calculations over longer periods of time. After x6, ships that were only a few parts started to kill themselves.   I will see what I can do though, this is a good idea. Really, for the super long non-atmo burns, thrust-on-rails (like the PersistentThrust mod) is a good place to go. Not sure when it was last updated.

**Comment by ntwest** [comment]
One thing I was thinking of was to maybe do kind of what Kerbal Joint Reinforcement does - when at higher phys warp rates, increase the strength of the connecting joints.

**Comment by ntwest** [comment]
I'm going to try to get to this but probably not for the KSP 1.3 release. I'm working on porting the UI over to unity first.

**Comment by ntwest** [comment]
In 2.8.2 I allowed up to x10 physwarp. Seems to usually blows up the ship. I'm still thinking about how I'd programatically know if a ship would be unstable or not at high physwarp rates.

**Comment by ntwest** [comment]
I'm going to close this out as a won't do. The new hyper warp rate options might do some of what you want to do here, but I haven't had much time to work on the mod and likely won't in the future.
